filebeat.registry_file: /var/log/containers/filebeat_registry

filebeat.prospectors:
-
  paths:
    - "/var/log/containers/*.log"
  symlinks: true
  json.message_key: log
  json.keys_under_root: true
  json.add_error_key: true
  multiline.pattern: '^\s'
  multiline.match: after
  document_type: kube-logs
  fields:
    host: ${FILEBEAT_HOST:${HOSTNAME}}
  fields_under_root: true


output.kafka:
  # initial brokers for reading cluster metadata"
  hosts: ${KAFKA_HOSTS:?No kafka host configured. Use env var KAFKA_HOSTS to set hosts.}
  # message topic selection + partitioning
  topic: 'flamingo-logs-%{[type]}'
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  
logging.level: ${LOG_LEVEL:error}

